#pragma once

#define CONF_I2C_SLAVE_MODULE		SERCOM2

#define CONF_UART_MODULE		SERCOM1
#define CONF_UART_SERCOM_MUX_SETTING	USART_RX_1_TX_0_XCK_1
#define CONF_UART_SERCOM_PINMUX_PAD0	PINMUX_PA16C_SERCOM1_PAD0
#define CONF_UART_SERCOM_PINMUX_PAD1	PINMUX_PA17C_SERCOM1_PAD1
#define CONF_UART_SERCOM_PINMUX_PAD2	PINMUX_UNUSED
#define CONF_UART_SERCOM_PINMUX_PAD3	PINMUX_UNUSED

#define UDD_CLOCK_GEN      GCLK_GENERATOR_1
#define UDD_CLOCK_SOURCE   SYSTEM_CLOCK_SOURCE_DFLL

#define CONFIG_SLEEPMGR_ENABLE
